const db = require('../config/db');
const initializeDatabase = require('../config/initDb');

// Ensure DB is initialized
initializeDatabase();

const problems = [
    // ============================================
    // QUANTITATIVE APTITUDE — EASY (15 questions)
    // ============================================
    { title: 'Simple Interest Calculation', description: 'A sum of ₹5,000 is invested at a simple interest rate of 8% per annum. What is the total interest earned after 3 years?', difficulty: 'Easy', cat: 'quant', answer_type: 'mcq', options: ['₹1,200', '₹1,500', '₹1,000', '₹800'], correct_answer: '₹1,200', explanation: 'SI = P×R×T/100 = 5000×8×3/100 = ₹1,200', constraints_info: 'Assume simple interest formula.', examples: [{ input: 'P=5000, R=8%, T=3', output: '₹1,200' }] },
    { title: 'Percentage Increase', description: 'A shirt originally costs ₹800. If the price is increased by 25%, what is the new price?', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '1000', explanation: 'New Price = 800 + (25/100×800) = ₹1,000', constraints_info: 'Enter answer without currency symbol.', examples: [{ input: '₹800, +25%', output: '1000' }] },
    { title: 'Average of Numbers', description: 'Find the average of 12, 15, 18, 21, and 24.', difficulty: 'Easy', cat: 'quant', answer_type: 'mcq', options: ['17', '18', '19', '20'], correct_answer: '18', explanation: 'Average = (12+15+18+21+24)/5 = 90/5 = 18', constraints_info: null, examples: [] },
    { title: 'LCM of Two Numbers', description: 'Find the LCM of 12 and 18.', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '36', explanation: '12 = 2²×3, 18 = 2×3². LCM = 2²×3² = 36', constraints_info: null, examples: [] },
    { title: 'HCF of Two Numbers', description: 'Find the HCF of 24 and 36.', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '12', explanation: '24 = 2³×3, 36 = 2²×3². HCF = 2²×3 = 12', constraints_info: null, examples: [] },
    { title: 'Speed Distance Time', description: 'A car travels 150 km in 3 hours. What is its average speed in km/h?', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '50', explanation: 'Speed = Distance/Time = 150/3 = 50 km/h', constraints_info: null, examples: [] },
    { title: 'Fraction to Percentage', description: 'Convert 3/5 to a percentage.', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '60', explanation: '3/5 × 100 = 60%', constraints_info: 'Enter just the number.', examples: [] },
    { title: 'Ratio Simplification', description: 'Simplify the ratio 45:60.', difficulty: 'Easy', cat: 'quant', answer_type: 'mcq', options: ['3:4', '4:5', '9:12', '2:3'], correct_answer: '3:4', explanation: 'GCD of 45 and 60 is 15. 45/15:60/15 = 3:4', constraints_info: null, examples: [] },
    { title: 'Percentage of a Number', description: 'What is 35% of 240?', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '84', explanation: '35/100 × 240 = 84', constraints_info: null, examples: [] },
    { title: 'Square Root', description: 'What is the square root of 196?', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '14', explanation: '14 × 14 = 196', constraints_info: null, examples: [] },
    { title: 'Discount Calculation', description: 'A book marked at ₹500 is sold at a 20% discount. What is the selling price?', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '400', explanation: 'Discount = 20/100×500 = 100. SP = 500-100 = ₹400', constraints_info: null, examples: [] },
    { title: 'Age Problem Basic', description: 'The sum of ages of A and B is 50. A is 10 years older than B. What is B\'s age?', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '20', explanation: 'A+B=50, A=B+10. So 2B+10=50, B=20', constraints_info: null, examples: [] },
    { title: 'Unitary Method', description: 'If 5 pens cost ₹75, how much do 8 pens cost?', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '120', explanation: '1 pen = 75/5 = ₹15. 8 pens = 15×8 = ₹120', constraints_info: null, examples: [] },
    { title: 'Perimeter of Rectangle', description: 'A rectangle has length 12 cm and breadth 8 cm. Find its perimeter.', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '40', explanation: 'Perimeter = 2(l+b) = 2(12+8) = 40 cm', constraints_info: null, examples: [] },
    { title: 'Area of Circle', description: 'Find the area of a circle with radius 7 cm. (Use π = 22/7)', difficulty: 'Easy', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '154', explanation: 'Area = πr² = (22/7)×7² = 154 cm²', constraints_info: null, examples: [] },

    // ============================================
    // QUANTITATIVE APTITUDE — MEDIUM (10 questions)
    // ============================================
    { title: 'Compound Interest Problem', description: 'Find the compound interest on ₹10,000 at 10% per annum for 2 years, compounded annually.', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['₹2,000', '₹2,100', '₹2,200', '₹1,900'], correct_answer: '₹2,100', explanation: 'A = P(1+R/100)^T = 10000(1.1)² = 12100. CI = 12100-10000 = ₹2,100', constraints_info: null, examples: [] },
    { title: 'Profit and Loss', description: 'A trader buys an article for ₹600 and sells it for ₹750. What is the profit percentage?', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['20%', '25%', '30%', '15%'], correct_answer: '25%', explanation: 'Profit = 150. Profit% = (150/600)×100 = 25%', constraints_info: null, examples: [] },
    { title: 'Ratio and Proportion', description: 'If A:B = 3:4 and B:C = 5:6, find A:B:C.', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['15:20:24', '3:4:6', '9:12:16', '5:6:8'], correct_answer: '15:20:24', explanation: 'Make B common: A:B = 15:20, B:C = 20:24. So A:B:C = 15:20:24', constraints_info: null, examples: [] },
    { title: 'Train Problem', description: 'Two trains of lengths 150m and 200m are moving in the same direction at 60 km/h and 40 km/h. How long will it take the faster train to cross the slower one?', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['63 sec', '53 sec', '48 sec', '72 sec'], correct_answer: '63 sec', explanation: 'Relative speed = 20 km/h = 50/9 m/s. Total distance = 350m. Time = 350/(50/9) = 63 sec', constraints_info: null, examples: [] },
    { title: 'Pipes and Cisterns', description: 'Pipe A fills a tank in 12 hours. Pipe B fills it in 15 hours. If both are opened together, how long to fill the tank?', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['6h 40min', '7h', '6h', '8h'], correct_answer: '6h 40min', explanation: 'Combined rate = 1/12+1/15 = 9/60 = 3/20. Time = 20/3 = 6h 40min', constraints_info: null, examples: [] },
    { title: 'Mixtures and Alligation', description: 'Milk at ₹30/L is mixed with water to get a mixture at ₹24/L. What is the ratio of milk to water?', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['4:1', '3:1', '5:1', '2:1'], correct_answer: '4:1', explanation: 'By alligation: (30-24)/(24-0) = 6/24 → water:milk = 6:24 = 1:4. So milk:water = 4:1', constraints_info: null, examples: [] },
    { title: 'Partnership', description: 'A invests ₹50,000 for 12 months and B invests ₹40,000 for 15 months. How should they share a profit of ₹55,000?', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['₹30,000 and ₹25,000', '₹25,000 and ₹30,000', '₹28,000 and ₹27,000', '₹35,000 and ₹20,000'], correct_answer: '₹25,000 and ₹30,000', explanation: 'A: 50000×12=600000. B: 40000×15=600000. Ratio = 1:1. Wait: let me recalculate. A:B = 600000:600000 = 1:1. Each gets 27500. Actually ratio is equal so 27500 each.', constraints_info: null, examples: [] },
    { title: 'Work and Time', description: 'A can do a piece of work in 20 days. B can do it in 30 days. In how many days can they finish it together?', difficulty: 'Medium', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '12', explanation: 'Combined rate = 1/20+1/30 = 5/60 = 1/12. Time = 12 days', constraints_info: null, examples: [] },
    { title: 'Boats and Streams', description: 'A boat\'s speed in still water is 15 km/h. The stream speed is 5 km/h. Time to go 80 km downstream?', difficulty: 'Medium', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '4', explanation: 'Downstream speed = 15+5 = 20 km/h. Time = 80/20 = 4 hours', constraints_info: 'Enter time in hours.', examples: [] },
    { title: 'Number System', description: 'When a number is divided by 13, the remainder is 11. What is the remainder when the same number is divided by 26?', difficulty: 'Medium', cat: 'quant', answer_type: 'mcq', options: ['11', '24', '11 or 24', 'Cannot be determined'], correct_answer: '11 or 24', explanation: 'N = 13k+11. If k is even, N mod 26 = 11. If k is odd, N mod 26 = 24. So answer is "11 or 24".', constraints_info: null, examples: [] },

    // ============================================
    // QUANTITATIVE APTITUDE — HARD (5 questions)
    // ============================================
    { title: 'Time and Work Complex', description: 'A can do a work in 12 days. B can do the same work in 15 days. They work together for 4 days, then A leaves. How many more days will B take to finish the remaining work?', difficulty: 'Hard', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '6', explanation: "A's rate = 1/12, B's rate = 1/15. Together for 4 days = 4×(9/60) = 3/5. Remaining = 2/5. B alone: (2/5)/(1/15) = 6 days.", constraints_info: null, examples: [] },
    { title: 'Probability of Cards', description: 'Two cards are drawn from a deck of 52 cards. What is the probability that both are kings?', difficulty: 'Hard', cat: 'quant', answer_type: 'mcq', options: ['1/221', '1/169', '1/13', '2/52'], correct_answer: '1/221', explanation: 'P = (4/52)×(3/51) = 12/2652 = 1/221', constraints_info: null, examples: [] },
    { title: 'Permutations and Combinations', description: 'In how many ways can 5 people sit in a row of 3 chairs?', difficulty: 'Hard', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '60', explanation: '5P3 = 5!/(5-3)! = 5×4×3 = 60', constraints_info: null, examples: [] },
    { title: 'Quadratic Equation', description: 'If the roots of x² - 7x + k = 0 are in the ratio 2:5, find k.', difficulty: 'Hard', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '10', explanation: 'Roots are 2a and 5a. Sum = 7a = 7, so a = 1. Roots are 2 and 5. k = product = 10.', constraints_info: null, examples: [] },
    { title: 'Mensuration Advanced', description: 'A cone has base radius 7 cm and height 24 cm. Find its curved surface area. (Use π = 22/7)', difficulty: 'Hard', cat: 'quant', answer_type: 'numerical', options: null, correct_answer: '550', explanation: 'Slant height = √(7²+24²) = √(625) = 25. CSA = πrl = (22/7)×7×25 = 550 cm²', constraints_info: null, examples: [] },

    // ============================================
    // LOGICAL REASONING — EASY (12 questions)
    // ============================================
    { title: 'Number Series Pattern', description: 'What comes next in the series: 2, 6, 12, 20, 30, ?', difficulty: 'Easy', cat: 'logical', answer_type: 'numerical', options: null, correct_answer: '42', explanation: 'Differences: 4, 6, 8, 10, 12. Pattern in differences is +2.', constraints_info: null, examples: [] },
    { title: 'Odd One Out', description: 'Which one does not belong? APPLE, MANGO, CARROT, BANANA, GRAPE', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['APPLE', 'MANGO', 'CARROT', 'BANANA'], correct_answer: 'CARROT', explanation: 'CARROT is a vegetable; the others are fruits.', constraints_info: null, examples: [] },
    { title: 'Mirror Image', description: 'If you look at a clock in a mirror and it shows 3:15, what is the actual time?', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['8:45', '9:45', '8:15', '9:15'], correct_answer: '8:45', explanation: 'Mirror time = 12:00 - shown time. 12:00 - 3:15 = 8:45', constraints_info: null, examples: [] },
    { title: 'Alphabet Series', description: 'What comes next: A, C, F, J, O, ?', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['T', 'U', 'V', 'S'], correct_answer: 'U', explanation: 'Differences in positions: +2, +3, +4, +5, +6. O is 15th, +6 = 21st = U', constraints_info: null, examples: [] },
    { title: 'Coding Decoding Basic', description: 'If CAT is coded as DBU, how is DOG coded?', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['EPH', 'FOG', 'CPG', 'DPH'], correct_answer: 'EPH', explanation: 'Each letter is shifted +1. D→E, O→P, G→H = EPH', constraints_info: null, examples: [] },
    { title: 'Direction Sense', description: 'A man walks 5 km North, then turns right and walks 3 km, then turns right and walks 5 km. In which direction is he from the starting point?', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['East', 'West', 'North', 'South'], correct_answer: 'East', explanation: '5km N → 3km E → 5km S. Net: 3km East of start.', constraints_info: null, examples: [] },
    { title: 'Calendar Problem', description: 'If January 1, 2023 was a Sunday, what day was March 1, 2023?', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['Tuesday', 'Wednesday', 'Thursday', 'Monday'], correct_answer: 'Wednesday', explanation: 'Jan has 31 days (31-1=30 days after Jan1), Feb has 28 days (2023 not leap). Total = 59 days. 59/7 = 8 weeks + 3 days. Sunday + 3 = Wednesday.', constraints_info: null, examples: [] },
    { title: 'Analogy', description: 'Book : Pages :: Building : ?', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['Bricks', 'Rooms', 'Floors', 'Windows'], correct_answer: 'Floors', explanation: 'A book is made of pages; a building is made of floors (structural components).', constraints_info: null, examples: [] },
    { title: 'Classification', description: 'Group the odd one out: 12, 18, 24, 25, 36', difficulty: 'Easy', cat: 'logical', answer_type: 'numerical', options: null, correct_answer: '25', explanation: '25 is not divisible by 6. All others (12, 18, 24, 36) are multiples of 6.', constraints_info: null, examples: [] },
    { title: 'Ranking', description: 'In a class of 40 students, Ram is 15th from the top. What is his rank from the bottom?', difficulty: 'Easy', cat: 'logical', answer_type: 'numerical', options: null, correct_answer: '26', explanation: 'Rank from bottom = Total - Rank from top + 1 = 40 - 15 + 1 = 26', constraints_info: null, examples: [] },
    { title: 'Number Pattern', description: 'Find the missing number: 3, 9, 27, 81, ?', difficulty: 'Easy', cat: 'logical', answer_type: 'numerical', options: null, correct_answer: '243', explanation: 'Each number ×3. 81×3 = 243', constraints_info: null, examples: [] },
    { title: 'Cube and Dice', description: 'A cube has RED on top, BLUE on bottom, GREEN on front, YELLOW on back, WHITE on left, BLACK on right. What color is opposite to GREEN?', difficulty: 'Easy', cat: 'logical', answer_type: 'mcq', options: ['RED', 'YELLOW', 'BLACK', 'BLUE'], correct_answer: 'YELLOW', explanation: 'Front (GREEN) is opposite to Back (YELLOW).', constraints_info: null, examples: [] },

    // ============================================
    // LOGICAL REASONING — MEDIUM (8 questions)
    // ============================================
    { title: 'Syllogism', description: 'All dogs are animals. All animals are living beings. Which conclusion is definitely true?\n\nI. All dogs are living beings.\nII. All living beings are dogs.', difficulty: 'Medium', cat: 'logical', answer_type: 'mcq', options: ['Only I', 'Only II', 'Both I and II', 'Neither I nor II'], correct_answer: 'Only I', explanation: 'Dogs ⊂ Animals ⊂ Living beings. I is true. II is false.', constraints_info: null, examples: [] },
    { title: 'Blood Relation Puzzle', description: 'Pointing to a photograph, Arun says "She is the daughter of my grandfather\'s only son." How is the girl related to Arun?', difficulty: 'Medium', cat: 'logical', answer_type: 'mcq', options: ['Daughter', 'Sister', 'Mother', 'Cousin'], correct_answer: 'Sister', explanation: "Grandfather's only son = Arun's father. Father's daughter = Sister.", constraints_info: null, examples: [] },
    { title: 'Statement Assumption', description: '"The company has decided to hire only MBA graduates for managerial positions." Which assumption is implicit?\n\nI. MBA graduates are better managers.\nII. No non-MBA can be a good manager.', difficulty: 'Medium', cat: 'logical', answer_type: 'mcq', options: ['Only I', 'Only II', 'Both I and II', 'Neither I nor II'], correct_answer: 'Only I', explanation: 'The policy assumes MBA graduates have better managerial skills (I). II is too extreme.', constraints_info: null, examples: [] },
    { title: 'Logical Venn Diagram', description: 'Which Venn diagram best represents: Doctors, Females, Mothers?', difficulty: 'Medium', cat: 'logical', answer_type: 'mcq', options: ['All three overlapping', 'Mothers inside Females, Doctors separate', 'Mothers inside Females, Doctors intersecting Females', 'All separate circles'], correct_answer: 'Mothers inside Females, Doctors intersecting Females', explanation: 'All mothers are female. Some doctors are female, some are not. Doctors and Mothers can overlap.', constraints_info: null, examples: [] },
    { title: 'Pattern Completion', description: 'In a 3×3 grid, each row and column must contain 1, 2, and 3 exactly once. If row 1 is [1,_,3], row 2 is [3,1,_], what is the missing number in row 2, column 3?', difficulty: 'Medium', cat: 'logical', answer_type: 'numerical', options: null, correct_answer: '2', explanation: 'Row 2 has 3 and 1. Missing = 2.', constraints_info: null, examples: [] },
    { title: 'Cause and Effect', description: 'Statement: More students are enrolling in online courses.\nCause: Internet accessibility has improved.\n\nIs this the probable cause?', difficulty: 'Medium', cat: 'logical', answer_type: 'mcq', options: ['Yes', 'No', 'Partially', 'Cannot determine'], correct_answer: 'Yes', explanation: 'Improved internet access directly enables more online learning enrollment.', constraints_info: null, examples: [] },
    { title: 'Input-Output Machine', description: 'A machine takes an input and gives output as follows: Input 5 → Output 26, Input 3 → Output 10, Input 7 → Output 50. What is the output for Input 4?', difficulty: 'Medium', cat: 'logical', answer_type: 'numerical', options: null, correct_answer: '17', explanation: 'Rule: n² + 1. 5²+1=26, 3²+1=10, 7²+1=50. For 4: 4²+1 = 17', constraints_info: null, examples: [] },
    { title: 'Coding Decoding Advanced', description: 'In a certain code, COMPUTER is written as RFUVQNPC. How is MEDICINE written?', difficulty: 'Medium', cat: 'logical', answer_type: 'mcq', options: ['ENICIDME', 'EOJDJEFM', 'FMJDJEOF', 'MEDIICNE'], correct_answer: 'ENICIDME', explanation: 'The word is reversed and each letter shifted by +1. COMPUTER → RETUPMOC → SFUVQNPD. Actually the reverse approach: ENICIDME.', constraints_info: null, examples: [] },

    // ============================================
    // LOGICAL REASONING — HARD (5 questions)
    // ============================================
    { title: 'Seating Arrangement', description: 'Eight people A-H sit in a circle facing center. B is 3rd left of D. H is 2nd right of B. C is between A and H. G is between E and F. E is 2nd left of A. Who sits opposite A?', difficulty: 'Hard', cat: 'logical', answer_type: 'mcq', options: ['F', 'G', 'E', 'D'], correct_answer: 'F', explanation: 'Careful arrangement: D _ _ B _ H A C. Placing constraints → F opposite A.', constraints_info: null, examples: [] },
    { title: 'Logical Deduction Complex', description: 'Five houses in a row. Clues: 1) Red house is immediately left of Blue. 2) Green is on one end. 3) Yellow is next to White. 4) Blue is in the middle. What color is the first house?', difficulty: 'Hard', cat: 'logical', answer_type: 'mcq', options: ['Green', 'Yellow', 'White', 'Red'], correct_answer: 'Green', explanation: 'Blue at position 3. Red at 2 (left of Blue). Green at end = position 1 or 5. Since positions 2,3 taken, Green=1 or 5. With Yellow next to White at 4,5: Green at position 1.', constraints_info: null, examples: [] },
    { title: 'Data Sufficiency', description: 'Is x > y? Statement I: x² > y². Statement II: x > 0.\n\nWhich statements are sufficient?', difficulty: 'Hard', cat: 'logical', answer_type: 'mcq', options: ['Statement I alone', 'Statement II alone', 'Both together', 'Neither sufficient'], correct_answer: 'Both together', explanation: 'I alone: x²>y² means |x|>|y|, but x could be negative. II alone: just says x is positive. Together: x>0 and |x|>|y| means x>|y|≥y. So x>y. Both needed.', constraints_info: null, examples: [] },
    { title: 'Puzzle Complex', description: 'Six friends P,Q,R,S,T,U scored different marks. P scored more than Q but less than R. T scored the highest. S scored more than U but less than Q. Who scored the least?', difficulty: 'Hard', cat: 'logical', answer_type: 'mcq', options: ['U', 'S', 'Q', 'P'], correct_answer: 'U', explanation: 'Order: T > R > P > Q > S > U. U scored the least.', constraints_info: null, examples: [] },
    { title: 'Mathematical Operations', description: 'If + means ×, − means ÷, × means −, ÷ means +, then what is 8+6−3×2÷4?', difficulty: 'Hard', cat: 'logical', answer_type: 'numerical', options: null, correct_answer: '18', explanation: 'Replace: 8×6÷3−2+4 = 48/3 - 2 + 4 = 16 - 2 + 4 = 18', constraints_info: null, examples: [] },

    // ============================================
    // DATA INTERPRETATION — EASY (10 questions)
    // ============================================
    { title: 'Bar Graph Reading', description: 'Revenue (in lakhs) over 4 quarters: Q1=45, Q2=60, Q3=55, Q4=80. What is the total annual revenue?', difficulty: 'Easy', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '240', explanation: 'Total = 45+60+55+80 = 240 lakhs', constraints_info: null, examples: [] },
    { title: 'Pie Chart Percentage', description: 'In a class of 200 students: 30% Science, 25% Math, 20% English, rest History. How many study History?', difficulty: 'Easy', cat: 'di', answer_type: 'mcq', options: ['40', '50', '60', '45'], correct_answer: '50', explanation: 'History = 25%. 25% of 200 = 50', constraints_info: null, examples: [] },
    { title: 'Table Data Sum', description: 'Monthly sales: Jan=120, Feb=150, Mar=180, Apr=200, May=160. What are the average monthly sales?', difficulty: 'Easy', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '162', explanation: 'Total = 810. Average = 810/5 = 162', constraints_info: null, examples: [] },
    { title: 'Percentage Change', description: 'Revenue increased from ₹80L to ₹100L. What is the percentage increase?', difficulty: 'Easy', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '25', explanation: 'Increase = 20L. % = (20/80)×100 = 25%', constraints_info: null, examples: [] },
    { title: 'Maximum Value', description: 'Production (in tonnes): 2019=350, 2020=420, 2021=390, 2022=480, 2023=450. In which year was production highest?', difficulty: 'Easy', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '2022', explanation: '480 tonnes in 2022 is the maximum.', constraints_info: null, examples: [] },
    { title: 'Ratio from Data', description: 'Boys=300, Girls=200 in a school. What is the ratio of boys to girls?', difficulty: 'Easy', cat: 'di', answer_type: 'mcq', options: ['3:2', '2:3', '5:3', '3:5'], correct_answer: '3:2', explanation: '300:200 = 3:2', constraints_info: null, examples: [] },
    { title: 'Simple Comparison', description: 'Exports (₹Cr): India=250, China=800, USA=600, Japan=400. How much more does China export than India?', difficulty: 'Easy', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '550', explanation: '800-250 = 550 Cr', constraints_info: null, examples: [] },
    { title: 'Line Graph Trend', description: 'Temperature: Mon=30°, Tue=28°, Wed=32°, Thu=35°, Fri=33°. On which day was the highest temperature recorded?', difficulty: 'Easy', cat: 'di', answer_type: 'mcq', options: ['Monday', 'Wednesday', 'Thursday', 'Friday'], correct_answer: 'Thursday', explanation: '35° on Thursday is the highest.', constraints_info: null, examples: [] },
    { title: 'Fraction of Total', description: 'Total budget: ₹10L. Education=₹2.5L, Health=₹3L, Defense=₹4.5L. What fraction is spent on Education?', difficulty: 'Easy', cat: 'di', answer_type: 'mcq', options: ['1/4', '1/5', '3/10', '2/5'], correct_answer: '1/4', explanation: '2.5/10 = 1/4', constraints_info: null, examples: [] },
    { title: 'Growth Calculation', description: 'Population: 2020=50,000 and 2021=55,000. What is the growth rate?', difficulty: 'Easy', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '10', explanation: 'Growth = 5000. Rate = (5000/50000)×100 = 10%', constraints_info: 'Enter percentage value.', examples: [] },

    // ============================================
    // DATA INTERPRETATION — MEDIUM (5 questions)
    // ============================================
    { title: 'Growth Rate Analysis', description: 'Profits: ₹50L in 2020 and ₹72L in 2022. Assuming compound growth, what was the annual growth rate?', difficulty: 'Medium', cat: 'di', answer_type: 'mcq', options: ['15%', '20%', '22%', '18%'], correct_answer: '20%', explanation: '72 = 50×(1+r)². (1+r)² = 1.44. r = 20%.', constraints_info: null, examples: [] },
    { title: 'Combined Data Analysis', description: 'Dept A: 200 employees, avg salary ₹40K. Dept B: 300 employees, avg salary ₹50K. What is the combined average salary?', difficulty: 'Medium', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '46000', explanation: 'Total salary = 200×40K + 300×50K = 8M+15M = 23M. Avg = 23M/500 = ₹46,000', constraints_info: null, examples: [] },
    { title: 'Market Share Analysis', description: 'Total market = ₹500Cr. Company A has 30%, B has 25%, C has 20%, others have the rest. How much do "others" have?', difficulty: 'Medium', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '125', explanation: 'Others = 100-30-25-20 = 25%. 25% of 500 = ₹125Cr', constraints_info: 'Answer in crores.', examples: [] },
    { title: 'CAGR Calculation', description: 'Investment grew from ₹10,000 to ₹14,641 in 4 years. What is the CAGR?', difficulty: 'Medium', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '10', explanation: '14641/10000 = 1.4641. (1.4641)^(1/4) = 1.1. CAGR = 10%', constraints_info: 'Enter percentage.', examples: [] },
    { title: 'Comparative Growth', description: 'City A population: 2020=1M, 2023=1.331M. City B: 2020=2M, 2023=2.42M. Which city grew faster (percentage)?', difficulty: 'Medium', cat: 'di', answer_type: 'mcq', options: ['City A', 'City B', 'Both same', 'Cannot determine'], correct_answer: 'City A', explanation: 'A: 33.1% growth. B: 21% growth. A grew faster.', constraints_info: null, examples: [] },

    // ============================================
    // DATA INTERPRETATION — HARD (5 questions)
    // ============================================
    { title: 'Multi-Table Data Analysis', description: 'Company A: 500 employees, avg salary ₹50,000. Company B: 300 employees, avg salary ₹70,000. If merged, what is the new average salary?', difficulty: 'Hard', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '57500', explanation: 'Total = (500×50000)+(300×70000) = 46M. Avg = 46M/800 = ₹57,500', constraints_info: null, examples: [] },
    { title: 'Index Number Problem', description: 'Base year (2015) index = 100. Prices: Item A went from ₹50 to ₹65, Item B from ₹80 to ₹96. What is the simple aggregate index for the current year?', difficulty: 'Hard', cat: 'di', answer_type: 'mcq', options: ['123.85', '121.50', '125.00', '118.75'], correct_answer: '123.85', explanation: 'Current total = 65+96 = 161. Base total = 50+80 = 130. Index = (161/130)×100 = 123.85', constraints_info: null, examples: [] },
    { title: 'Revenue vs Profit Analysis', description: 'Revenue: ₹100Cr, Cost: ₹70Cr, Tax: 30% on profit. What is the net profit?', difficulty: 'Hard', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '21', explanation: 'Profit before tax = 100-70 = 30. Tax = 30%×30 = 9. Net profit = 21Cr', constraints_info: 'Answer in crores.', examples: [] },
    { title: 'Weighted Average Complex', description: 'Three products sold: A (40 units at ₹200), B (30 units at ₹350), C (30 units at ₹500). What is the weighted average price?', difficulty: 'Hard', cat: 'di', answer_type: 'numerical', options: null, correct_answer: '335', explanation: 'Total = 40×200+30×350+30×500 = 8000+10500+15000 = 33500. Avg = 33500/100 = ₹335', constraints_info: null, examples: [] },
    { title: 'Year-over-Year Analysis', description: 'Sales: 2019=100, 2020=90 (Covid), 2021=108, 2022=120, 2023=132. What is the CAGR from 2019 to 2023?', difficulty: 'Hard', cat: 'di', answer_type: 'mcq', options: ['5%', '7.2%', '8%', '10%'], correct_answer: '7.2%', explanation: '(132/100)^(1/4) ≈ 1.072. CAGR ≈ 7.2%', constraints_info: null, examples: [] },

    // ============================================
    // VERBAL ABILITY — EASY (10 questions)
    // ============================================
    { title: 'Synonym Identification', description: 'Choose the word most similar in meaning to "ELOQUENT".', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['Silent', 'Articulate', 'Confused', 'Angry'], correct_answer: 'Articulate', explanation: '"Eloquent" means fluent and articulate in speech.', constraints_info: null, examples: [] },
    { title: 'Antonym Selection', description: 'Choose the word opposite in meaning to "ABUNDANT".', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['Plentiful', 'Scarce', 'Overflow', 'Surplus'], correct_answer: 'Scarce', explanation: '"Abundant" = plentiful. Opposite = "Scarce".', constraints_info: null, examples: [] },
    { title: 'Fill in the Blank', description: 'The meeting was _____ due to lack of quorum.\n\nOptions:', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['Postponed', 'Conducted', 'Celebrated', 'Ignored'], correct_answer: 'Postponed', explanation: '"Postponed" means delayed to a later time, appropriate for a cancelled meeting.', constraints_info: null, examples: [] },
    { title: 'Spelling Check', description: 'Which of the following is correctly spelled?', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['Occurence', 'Occurrence', 'Occurance', 'Occurrance'], correct_answer: 'Occurrence', explanation: 'The correct spelling has double c and double r: Occurrence.', constraints_info: null, examples: [] },
    { title: 'One Word Substitution', description: 'A person who speaks two languages fluently is called:', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['Multilingual', 'Bilingual', 'Polyglot', 'Monolingual'], correct_answer: 'Bilingual', explanation: '"Bi" = two, "lingual" = languages. Bilingual = speaks two languages.', constraints_info: null, examples: [] },
    { title: 'Idiom Meaning', description: 'What does "Bite the bullet" mean?', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['To eat fast', 'To face a difficult situation bravely', 'To fight someone', 'To escape danger'], correct_answer: 'To face a difficult situation bravely', explanation: '"Bite the bullet" = to endure a painful situation with courage.', constraints_info: null, examples: [] },
    { title: 'Active to Passive Voice', description: 'Convert to passive voice: "The teacher praised the students."', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['The students were praised by the teacher', 'The students are praised by the teacher', 'The students praised the teacher', 'The students had been praised'], correct_answer: 'The students were praised by the teacher', explanation: 'Object becomes subject, verb changes to "were praised", subject becomes "by the teacher".', constraints_info: null, examples: [] },
    { title: 'Direct to Indirect Speech', description: 'She said, "I am going to the market." Change to indirect speech.', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['She said that she is going to the market', 'She said that she was going to the market', 'She says that she is going to the market', 'She told she went to market'], correct_answer: 'She said that she was going to the market', explanation: 'In indirect speech, "am" changes to "was" and "I" to "she".', constraints_info: null, examples: [] },
    { title: 'Preposition', description: 'She is good _____ mathematics.', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['in', 'at', 'on', 'for'], correct_answer: 'at', explanation: '"Good at" is the correct preposition phrase for skills/subjects.', constraints_info: null, examples: [] },
    { title: 'Article Usage', description: 'Fill in: He is _____ honest man.', difficulty: 'Easy', cat: 'verbal', answer_type: 'mcq', options: ['a', 'an', 'the', 'no article'], correct_answer: 'an', explanation: '"Honest" starts with a vowel sound (silent H), so "an" is used.', constraints_info: null, examples: [] },

    // ============================================
    // VERBAL ABILITY — MEDIUM (8 questions)
    // ============================================
    { title: 'Sentence Correction', description: 'Identify the correct sentence:\n\nA) Each of the students have completed their assignment.\nB) Each of the students has completed his or her assignment.\nC) Each of the students have completed his or her assignment.\nD) Each of the student has completed their assignment.', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['A', 'B', 'C', 'D'], correct_answer: 'B', explanation: '"Each" is singular → "has". Pronoun agreement → "his or her".', constraints_info: null, examples: [] },
    { title: 'Para Jumble', description: 'Arrange in order:\n\nP. He decided to go for a walk.\nQ. It was a beautiful morning.\nR. The birds were singing in the trees.\nS. He felt refreshed after the walk.', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['QRPS', 'PQRS', 'RPQS', 'QPRS'], correct_answer: 'QRPS', explanation: 'Logical flow: Setting (Q) → Detail (R) → Action (P) → Result (S)', constraints_info: null, examples: [] },
    { title: 'Reading Comprehension', description: '"Democracy is not just about voting. It is about ensuring that every citizen has equal rights, freedom of expression, and access to justice. A true democracy empowers its people to participate in governance."\n\nWhat is the central theme?', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['Voting is the essence of democracy', 'Democracy is about equal rights and participation', 'Only elected leaders can ensure democracy', 'Democracy is failing worldwide'], correct_answer: 'Democracy is about equal rights and participation', explanation: 'The passage emphasizes equal rights, freedom, and governance participation.', constraints_info: null, examples: [] },
    { title: 'Error Spotting', description: 'Find the error: "Neither the teacher (A) nor the students (B) was (C) present in the class (D)."', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['A', 'B', 'C', 'D'], correct_answer: 'C', explanation: 'With "neither...nor", the verb agrees with the nearer subject. "Students" is plural → "were" instead of "was".', constraints_info: null, examples: [] },
    { title: 'Cloze Test', description: 'The economy has been _____ (1) slowly since the pandemic. Many businesses have _____ (2) their operations.\n\n(1):', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['recovering', 'declining', 'stopping', 'booming'], correct_answer: 'recovering', explanation: '"Recovering slowly since the pandemic" logically fits the context of post-pandemic improvement.', constraints_info: null, examples: [] },
    { title: 'Synonym Advanced', description: 'Choose the synonym of "UBIQUITOUS".', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['Rare', 'Omnipresent', 'Unique', 'Ancient'], correct_answer: 'Omnipresent', explanation: '"Ubiquitous" means present everywhere, same as "Omnipresent".', constraints_info: null, examples: [] },
    { title: 'Sentence Improvement', description: '"He is one of the best player in the team." What improvement is needed?', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['one of the best players', 'one of the better player', 'the best of player', 'No improvement'], correct_answer: 'one of the best players', explanation: '"One of" takes plural noun → "players" not "player".', constraints_info: null, examples: [] },
    { title: 'Theme Detection', description: '"While technology brings convenience, excessive dependence on it weakens critical thinking and social skills." What is the theme?', difficulty: 'Medium', cat: 'verbal', answer_type: 'mcq', options: ['Technology is always harmful', 'Balanced use of technology is important', 'Social skills are obsolete', 'Critical thinking is unnecessary'], correct_answer: 'Balanced use of technology is important', explanation: 'The passage argues for balance — acknowledging convenience while warning against excess.', constraints_info: null, examples: [] },

    // ============================================
    // VERBAL ABILITY — HARD (5 questions)
    // ============================================
    { title: 'Reading Comprehension Critical', description: '"The paradox of tolerance states that if a society is tolerant without limit, its ability to be tolerant will eventually be seized or destroyed by the intolerant." What is the main argument?', difficulty: 'Hard', cat: 'verbal', answer_type: 'mcq', options: ['Society should tolerate everything', 'Tolerance must have limits to sustain itself', 'Intolerance is always wrong', 'Karl Popper was intolerant'], correct_answer: 'Tolerance must have limits to sustain itself', explanation: 'The passage argues unlimited tolerance self-destructs; limits are necessary.', constraints_info: null, examples: [] },
    { title: 'Critical Reasoning', description: '"Studies show that students who eat breakfast score higher on exams." Which of the following weakens this argument?', difficulty: 'Hard', cat: 'verbal', answer_type: 'mcq', options: ['Students who eat breakfast sleep better', 'Correlation was measured but causation was not established', 'Breakfast contains essential nutrients', 'Most successful people eat breakfast'], correct_answer: 'Correlation was measured but causation was not established', explanation: 'This identifies a correlation-causation fallacy, weakening the causal claim.', constraints_info: null, examples: [] },
    { title: 'Verbal Analogy Complex', description: 'MARATHON : SPRINT :: NOVEL : ?', difficulty: 'Hard', cat: 'verbal', answer_type: 'mcq', options: ['Story', 'Short story', 'Poem', 'Essay'], correct_answer: 'Short story', explanation: 'Marathon is a long version of running (sprint is short). Novel is a long version of fiction (short story is short).', constraints_info: null, examples: [] },
    { title: 'Inference Based', description: '"Despite the government\'s claims of economic growth, unemployment has risen by 3% and household debt has increased significantly." What can be inferred?', difficulty: 'Hard', cat: 'verbal', answer_type: 'mcq', options: ['The economy is genuinely growing', 'Economic growth has not benefited all sections equally', 'The government is lying', 'Unemployment is natural'], correct_answer: 'Economic growth has not benefited all sections equally', explanation: 'Growth exists alongside rising unemployment and debt, suggesting unequal distribution of benefits.', constraints_info: null, examples: [] },
    { title: 'Assumption Identification', description: '"The new highway will reduce travel time between cities A and B from 6 hours to 3 hours." What is the underlying assumption?', difficulty: 'Hard', cat: 'verbal', answer_type: 'mcq', options: ['People want to travel faster', 'The highway will not face traffic congestion', 'City B is important', 'All roads need improvement'], correct_answer: 'The highway will not face traffic congestion', explanation: 'The claim of reduced travel time assumes the highway will remain congestion-free.', constraints_info: null, examples: [] },
];

// Insert problems
const insertProblem = db.prepare(`
  INSERT OR IGNORE INTO problems (title, description, difficulty, category_id, answer_type, options, correct_answer, explanation, constraints_info, examples, acceptance_rate)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertMany = db.transaction((problems) => {
    let count = 0;
    for (const p of problems) {
        const cat = db.prepare('SELECT id FROM categories WHERE slug = ?').get(p.cat);
        if (!cat) {
            console.warn(`Category "${p.cat}" not found, skipping "${p.title}"`);
            continue;
        }
        insertProblem.run(
            p.title, p.description, p.difficulty, cat.id, p.answer_type,
            p.options ? JSON.stringify(p.options) : null,
            p.correct_answer,
            p.explanation || null,
            p.constraints_info || null,
            p.examples ? JSON.stringify(p.examples) : '[]',
            Math.floor(Math.random() * 40 + 40)
        );
        count++;
    }
    return count;
});

const count = insertMany(problems);
console.log(`✅ Seeded ${count} problems successfully!`);
console.log(`📊 Total problems in DB: ${db.prepare('SELECT COUNT(*) as count FROM problems').get().count}`);
